export const EMAIL = "marcinkrueger@gmail.com"
export const GITHUB = "https://github.com/marcol13"
export const LINKEDIN = "https://www.linkedin.com/in/marcin-krueger/"
export const LINKEDIN_EN = "https://www.linkedin.com/in/marcin-krueger/?locale=en_US"
export const TWITTER = ""
export const HASHNODE = "https://mkrueger.hashnode.dev"